### DISCUSSION TITLE
Using docker args with non-root user

### DISCUSSION THREAD

**Discussion by aedrax** [JonathonReinhart/scuba#199] [Q&A]
We're trying to use `docker_args: '--group-add dialout'` but it only adds the root user to dialout, is there a way to specify the user?

**Comment by haboustak** [comment]
scuba could make this easier on you, as it is already managing users and groups inside the container, but it may be possible using external environment variables and root hooks:

``` yaml
environment:
  USER:

hooks:
  root:
    script:
      - \[ -n "$USER" \] || ( echo "No USER in environment" ; exit 1 )
      - gpasswd -a $USER dialout
```

It would be nicer to do it without relying on the external env (e.g. `$SCUBA_USER`),  and even nicer to do it without the hook.
