### ISSUE TITLE
Allow `script` to be a single string value

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/scuba#102]
Currently, this is invalid:
```yaml
aliases:
  foo:
    image: xyz
    script: echo Hello
```
