### ISSUE TITLE
Scuba doesn't work with images that have USER set

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/scuba#109]

**Comment by mpdude** [comment]
I've been trying to use:

```yaml
image: none

aliases:
    yarn:
        image: node:12-alpine
        script: yarn install
```

Which results in `scubainit: GID 1000 already exists in /etc/group`.

Is this the same issue?
