### ISSUE TITLE
Concatenate lists imported from external YAML files

### ISSUE THREAD

**Issue by xanarin** [JonathonReinhart/scuba#127]
I have a use case where it would be extremely helpful to concatenate multiple lists from a different YAML file using Scuba's `!from_yaml` directive.

For example, I have the following Gitlab CI YAML configuration for my project:
```yaml
build_compA:
  stage: build
  tags:
    - docker
  script:
    - scons -C compA

build_compB:
  stage: build
  tags:
    - docker
  script: 
    - cd compB/
    - compB/gradlew -g .gradle -p compB lint
    - compB/gradlew -g .gradle -p compB test
```

Right now, I have two different Scuba aliases that reference these two CI jobs:
```yaml
aliases:
  build_compA: !from_yaml .gitlab-ci.yml build_compA
  build_compB: !from_yaml .gitlab-ci.yml build_compB
```

However, when I want to build both projects in the same bash invocation, I have to append multiple Scuba calls together:
```bash
$ scuba build_compA && scuba build_compB
```

---

It would make building all components simultaneously much easier if I could create an alias in my Scubafile that concatenated together both lists to create a single list to be run in the alias. This is a sample of what that could look like:
```yaml
aliases:
  build_all:
    script:
        - !from_yaml .gitlab-ci.yml build_compA
        - !from_yaml .gitlab-ci.yml build_compB
```
Or, maybe something more like:
```yaml
aliases:
  build_all:
    script: !from_yaml [.gitlab-ci.yml build_compA] [.gitlab-ci.yml build_compB]
```

Though I acknowledge that this could potentially lead to a user shooting themselves in the foot if they concatenate incompatible lists of commands, I think in some cases this functionality could be very helpful and make some Scubafiles and scuba invocations more succinct. Especially in cases where 7+ components need to be built at once, this would make the scuba invocation much simpler and eliminate the need to create a bash script just to build the project.

**Comment by JonathonReinhart** [comment]
I really like your first suggestion:
```yaml
aliases:
  build_all:
    script:
        - !from_yaml .gitlab-ci.yml build_compA
        - !from_yaml .gitlab-ci.yml build_compB
```

This is good because it introduces no new concepts to the yaml schema. Each list element would itself be a list from the other yamal file.

Implementing this should be nothing more than flattening the nested list (something that SCons does frequently).
