### ISSUE TITLE
Mount additional volumes

### ISSUE THREAD

**Issue by mpdude** [JonathonReinhart/scuba#140]
Would it make sense to allow mounting additional directories through `.scuba.yml`, or is it already possible to do so?

My use case is that I would like to run tools to fetch dependencies (like `yarn`, `maven`, `composer`, ...). In order to access private repositories through SSH, one easy solution would be to bind-mount `$SSH_AUTH_SOCK` into the container.

Also, depending on the tool, it might be valuable to mount cache directories for `yarn` or `maven` into the build container.

Example:

```yaml
image: none

environment:
  SSH_AUTH_SOCK: /tmp/ssh-auth.sock

aliases:
  yarn:
    image: node:12-alpine
    mount:
      - $SSH_AUTH_SOCK:/tmp/ssh-auth.sock
      - $HOME/.cache/yarn:/root/.cache/yarn
```

Does that make sense and if so, could you guide me as to which changes are probably necessary? I am not a Python programmer. In particular, it would be helpful to know how I could run a locally checked-out version of `scuba` from inside my build directory.

**Comment by xanarin** [comment]
@JonathonReinhart I believe this feature is now possible with the addition of the `docker_args:` directive in #177. The equivalent `.scuba.yml` file for the example posted above would be:
```yaml
image: none

environment:
  SSH_AUTH_SOCK: /tmp/ssh-auth.sock

aliases:
  yarn:
    image: node:12-alpine
    docker_args: '-v $SSH_AUTH_SOCK:/tmp/ssh-auth.sock -v $HOME/.cache/yarn:/root/.cache/yarn'
```

I think this issue can be closed.

**Comment by JonathonReinhart** [comment]
@xanarin While this *can* be done with `docker_args` I think there is still value in having a dedicated option in `.scuba.yml` for this (i.e. `volumes` or `mounts` as @mpdude suggested). So I'm going to leave this open.

I've started work on it (see #186) and would like to get released relatively quickly before a bunch of `.scuba.yml` files grow `docker_args: -v ...` entries.

**Comment by JonathonReinhart** [comment]
I currently have this feature working (#186) where the volumes are defined in the yaml like this:
```yaml
volumes:
  - /host/foo:/var/lib/foo
  - /host/bar:/var/lib/bar:ro
```
It's simple enough: each entry is just passed as `--volume` to `docker run`. The naive implementation works well enough.

I started thinking about the interaction between top-level volumes and per-alias volumes, and the way we used `!override` for `docker_args` (https://github.com/JonathonReinhart/scuba/pull/177#discussion_r677839728).

I'm not sure there is a real use-case, but currently there is no way to override a top-level mountpoint:
```yaml
volumes:
  - /host/foo:/var/lib/foo
aliases:
  dummy:
    volumes:
      - /a/different/place/foo:/var/lib/foo
```

At least there's no need to detect duplicate mount point definitions, as docker does this itself and throws an error:
```
$ docker run --rm -it -v /tmp/a/:/var/lib/foo -v /tmp/b/:/var/lib/foo debian:10
docker: Error response from daemon: Duplicate mount point: /var/lib/foo.
See 'docker run --help'.
```

I considered simply parsing the volume spec strings, and having scuba handle the override. The obvious implementation is to store them as a dictionary, where the key is the container-path, and then calling `dict.update()`. This made me wonder if a dictionary (mapping) would be a better yaml schema:
```yaml
volumes:
  /var/lib/foo: /host/foo
aliases:
  dummy:
    volumes:
      /var/lib/foo: /a/different/place/foo
```

A question would be how to handle *options* (e.g. `ro`). We could stick them on the end after a colon, but this feels a little odd:
```yaml
volumes:
  /var/lib/foo: /host/foo:ro
```

Maybe the better choice would be specific sub-keys:
```yaml
volumes:
  /var/lib/foo:
    hostpath: /host/foo
    options: ro,z
```

I guess it wouldn't be too hard to handle both the simple and elaborate styles:
```yaml
volumes:
  /var/lib/foo: /host/foo
  /var/lib/bar:
    hostpath: /host/bar
    options: ro,z
```

This is starting to look like [docker-compose](https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes)!

This is obviously a lot more work, but I think it seems pretty nice. Thoughts?

cc @xanarin @adamjseitz

**Comment by JonathonReinhart** [comment]
I updated #186 based on the above design, supporting both the simple and complex forms. I'd be happy for anyone to take a look at #186.

**Comment by xanarin** [comment]
My opinion is that scuba should only support the following form:
```yaml
volumes:
  - /host/foo:/var/lib/foo
  - /host/bar:/var/lib/bar:ro
  ```
  
I don't think adding a scuba-specific syntax for the mapping options (as proposed in your comment above) adds enough of a readability boost to offset having each user learn a scuba-specific syntax for mapping volumes. Since this isn't a `.gitlab-ci.yml` compatibility syntax, I don't think Scuba should have its own syntax when there is already an established (and well-documented) syntax for mapping volumes used by both the Docker CLI and `docker-compose.yml`. If a user that stumbles on a `.scuba.yml` file that looks like this:
```yaml
aliases:
  dummy:
    volumes:
      /var/lib/foo1:/var/lib/foo2:Z
```
they will be able to quickly google for something like "Z at the end of docker volume" and quickly access all of the Docker resources about volume mount options, whereas if a user sees the following `.scuba.yml`:
```yaml
aliases:
  dummy:
    volumes:
      /var/lib/foo: 
        hostpath: /a/different/place/foo
        options: Z
```
this user would be able to figure out what the "Z" means only after they figure out that Scuba is just concatenating the `key`, `hostpath`, and `options` together to pass to Docker on the user's behalf.

A bigger question (IMO) is whether Scuba will support variable/tilde expansion inside of the volume expression. One of the potential use-cases that this implementation could address is mapping in `~/.config/art/config.yml` so that we don't have to export the user's Gitlab PAT in the shell environment (how we're currently running `art` inside of Scuba). This will only be possible if Scuba (or the underlying shell command that it runs) provides expansion for `~` or `$HOME`, since this path is different on each user's machine.

> This is starting to look like docker-compose!

I mean, you're not wrong 😆

**Comment by JonathonReinhart** [comment]
Thanks for the feedback, @xanarin.

While it wasn't necessarily my primary motivation, I do think the readability improvement is helpful. I still often stumble when visually parsing a docker volume line like `/data/foo:/var/lib/foo`, not only because the colon makes a weak separator, but also because I have to ask myself "okay which one is the host/container path?"

While I agree that the docker volume syntax is more-established than this proposed scuba feature, I don't think that means it is better. In fact, docker is encouraging users to use the more readable and flexible [`--mount`](https://docs.docker.com/storage/bind-mounts/#choose-the--v-or---mount-flag) option instead of `--volume`. And `docker-compose` supports a [long syntax](https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax-3) that uses a similar style (although it uses a list instead of a dict keyed by container path as I propose).

I disagree that the `options: Z` syntax is difficult to understand or learn more about. It's (more) clear from the name that these are "volume options", and the user can easily follow the [scuba documentation](https://scuba--186.org.readthedocs.build/en/186/configuration.html#volumes) to the Docker documentation.

Your points about environment variable and tilde expansion are well-received. In fact, this is one of the motivating factors *against* sticking with the Docker volume syntax -- it would be less surprising to know that Scuba will interpret its own syntax, as opposed to modifying something that looks like it should be passed through directly to Docker. If Scuba has to interpret anything, I'd rather it interpret YAML format, rather than parse Docker constructs.

After careful consideration of your points, (and perhaps due to the fact that I already implemented it :laughing:), I'm going to merge #186 as-is. The feature will go in without variable expansion for now, but we can easily add that when the motivation arises.

Thanks again!

**Comment by xanarin** [comment]
Thanks for considering my feedback.

>  The feature will go in without variable expansion for now, but we can easily add that when the motivation arises.

As stated in my previous comment, I believe this motivation already exists. Many projects are using gitlab-art to collect artifacts and, at least on my program, we are getting our Gitlab token into the container by exporting it as an environmental variable in our `.bashrc` (or similar). Adding variable expansion in the new `volumes` directive would provide a more secure way to pass one's Gitlab token into the container; one could just add a volume mapping of `~/.config/art` or `$HOME/.config/art` to the Scuba alias. This would make the Gitlab token available in the container without exposing it to every program that the user runs from their shell.

AFAICT, now that Scuba uses the user's username (and therefore home directory path) inside the container, there is no way for a user to mount a directory under their home folder into the container in a way that will work on multiple people's development machines. I think the following syntax could provide that capability in an easy-to-parse way:
```yaml
image: debian:buster
aliases:
    ex1:
        volumes:
            ~/.config/art: ~/.config/art
        script:
            - cat $HOME/.config/art/config.yml
    ex2:
        volumes:
            $HOME/.config/art: $HOME/.config/art
        script:
            - cat $HOME/.config/art/config.yml
```
