### ISSUE TITLE
Cache YAML Files that are Referenced in !from_yaml Statements

### ISSUE THREAD

**Issue by xanarin** [JonathonReinhart/scuba#146]
## Problem
I am currently working on a large project that utilizes Scuba heavily. There are 27 scuba aliases in the `.scuba.yml` file, and all of the aliases have at least one `!from_yaml` directive in their definition. For example, many of the simple aliases look like this:
```yaml
product1_build:
  image: !from_yaml .gitlab-ci.yml product1_build.image
  script:
    - cd "$SCUBA_ROOT"
    - !from_yaml .gitlab-ci.yml product1_build.script
```

This means that there are 46 `!from_yaml` directives all referencing the same YAML file: `.gitlab-ci.yml`. Because Scuba re-parses this YAML file for every `!from_yaml`, this significantly slows down Scuba.

Tab completion is especially impacted by this; it can take almost 5 seconds for tab completion to complete. Since tab completion is mostly just a wrapper around `scuba --list-aliases`, we can use this command to benchmark tab completion:
```sh
$ time scuba --list-aliases
ALIAS             IMAGE
product1_build    debian:buster

real   0m4.784s
user   0m4.696s
sys    0m0.048s
```

## Suggested Solution
Scuba could cache files that have already been parsed in a previous `!from_yaml` invocation. This would eliminate the time needed to re-read and re-parse a file that has already been read and parsed.
