### ISSUE TITLE
Add Option to .scuba.yml to Run an Alias as Root

### ISSUE THREAD

**Issue by xanarin** [JonathonReinhart/scuba#147]
## Problem
Currently, one can run an alias as `root` in the container by specifying the `-r` or `--root` flag on the command line. However, there is not currently a way to specify this option in the `.scuba.yml` config file.

## Solution
A new option could be added to `.scuba.yml` to specify that a particular alias should run in the container as `root`:
```yaml
image: debian:buster
aliases:
  whoami:
    script:
      - whoami
  whoami_su:
    root: true
    script:
      - whoami
```

```bash
$ scuba whoami
scubauser

$ scuba whoami_su
root
```

EDIT: Remove ability to have top-level `root` node, as this could lead to unknowing misuse of Scuba and (AFAIK) doesn't have any current practical use-cases.
