### ISSUE TITLE
Add the ability to pass arguments to a multi-line alias

### ISSUE THREAD

**Issue by xanarin** [JonathonReinhart/scuba#148]
## Problem
On the project I'm currently working on, we have a lot of aliases that look like this:
```yaml
aliases:
    build_my_software:
        script:
            - cd "$SCUBA_ROOT"
            - make my_software
```

We use `cd "$SCUBA_ROOT"` to allow developers to run builds at the top-level from anywhere in the repository. Because this is a multi-line alias, Scuba does not allow one add additional arguments to the Scuba invocation:
```sh
$ scuba build_my_software MODE=debug
scuba: Additional arguments not allowed with multi-line aliases
```

This means that we have to create a number of extra scuba aliases to invoke every permutation of our potential Make arguments:
```yaml
aliases:
    build_my_software_debug:
        script:
            - cd "$SCUBA_ROOT"
            - make my_software MODE=debug
    build_my_software_release:
        script:
            - cd "$SCUBA_ROOT"
            - make my_software MODE=release
```

This very quickly becomes cumbersome and unmaintainable.

## Proposed Solution

AFAIK, the restriction of not allowing additional arguments was originally put in place because Scuba wouldn't know how to pass the additional arguments to the multi-line commands. My proposed solution to this is to have Scuba pass the additional arguments directly to the `/.scuba/command.sh` script. This would allow a user to create an alias like this:
```yaml
aliases:
    build_my_software:
        script:
            - cd "$SCUBA_ROOT"
            - make my_software "$@"
```

This would allow the user to invoke Scuba like this;
```sh
$ scuba build_my_software MODE=debug
make: building software in 'debug' mode
....
```

In the case where a user isn't aware of Scuba's ability to pass extra arguments to multi-line aliases, the extra arguments will be ignored. This should allow for progressive disclosure of complexity w.r.t. this feature.

**Comment by JonathonReinhart** [comment]
In your specific case, I think you could use `make`'s `-C` option and make this a single-line alias:
```yaml
aliases:
    build_my_software:
        script: make -C "$SCUBA_ROOT" my_software
```
This might be the general answer for other use cases requiring this behavior: use a single-line alias. I can't think of a case where moving a multi-line alias to a shell script (which can handle `"$@"`) wouldn't work.
