### ISSUE TITLE
Expand environmental variables in volume paths

### ISSUE THREAD

**Issue by xanarin** [JonathonReinhart/scuba#191]
A limitation of the solution that addressed #140 was that it did not support expanding environmental variables in volume parameters. This is important for use-cases where paths are different between each user's environment. For example, mapping in directories inside of a user's `/home` folder for user-specific configuration files. See [this comment](https://github.com/JonathonReinhart/scuba/issues/140#issuecomment-913812915) for more justification.

I would like Scuba to support a configuration like this:
```yaml
image: debian:buster
aliases:
    ex2:
        volumes:
            $HOME/.config/art: $HOME/.config/art
        script:
            - cat $HOME/.config/art/config.yml
```
