### ISSUE TITLE
volumes configuration defaults to root ownership if the file or directory at hostpath does not exist

### ISSUE THREAD

**Issue by haboustak** [JonathonReinhart/scuba#195]
Scuba's `volumes` configuration utilizes Docker's [bind-mount](https://docs.docker.com/storage/bind-mounts/) `--volume` feature which automatically creates `hostpath` as a directory if it doesn't exist when starting the container. This creates ownership problems because the Docker daemon creates the directory at `hostpath` as `root`.

**Reproduction configuration**
``` yaml
image: debian:11
volumes:
  ${PWD}/missing: ${PWD}/missing
aliases:
  test:
    script:
      - ls -ld missing
      - touch missing/test
```

``` bash
$ #rm -rf ./missing
$ scuba test
drwxr-xr-x 2 root root 4096 Dec  6 13:09 missing
touch: cannot touch 'missing/test': Permission denied
```

**Expected Behavior**
When starting a container with bind-mount volumes, Scuba should attempt to create a directory as the user when bind-mounting a non-existent `hostpath`.
1. If Scuba can create the directory without `root` it's **always** better, as both the current user and root will have access to the directory at `hostpath`.
2. If Scuba can't create the directory, then it's reasonable to fall back to Docker's default behavior without an error. Scuba should not modify file permissions at `hostpath`.
