### ISSUE TITLE
!from_yaml seems to break YAML merge key on mappings

### ISSUE THREAD

**Issue by fortenbt** [JonathonReinhart/scuba#198]
Mappings defined in other YAML files cannot be merged using the YAML merge key. When attempting this, the following error occurs.

```console
$ scuba foo
scuba: Config error: Error loading .scuba.yml: while constructing a mapping
  in ".scuba.yml", line 8, column 13
expected a mapping for merging, but found scalar
  in ".scuba.yml", line 3, column 22
```

**Background**

YAML mappings can be merged with with merge key `<<` (https://yaml.org/type/merge.html)

**Example**
The example in this issue uses the following files: `foo.yml`, `bar.yml`, and `.scuba.yml`

```yml
# foo.yml
aliases:
    foo:
        global-vars: &global-vars
            VERSION: "1.0"
        sub-vars: &sub-vars
            SUB_VERSION: "2.0"
        environment:
            <<: [ *global-vars, *sub-vars ]
```

```yml
# bar.yml
variables:
    VERSION: "1.0"

subvars:
    SUB_VERSION: "2.0"
```

```yml
# .scuba.yml (just foo.yml, except replacing the *-vars values with !from_yaml)
aliases:
    foo:
        global-vars: &global-vars
            !from_yaml bar.yml variables
        sub-vars: &sub-vars
            !from_yaml bar.yml subvars
        environment:
            <<: [ *global-vars, *sub-vars ]
```

*PyYAML Output*
```python
>>> import yaml
>>> yaml.load(open('foo.yml', 'r').read())
{'aliases': {'foo': {'global-vars': {'VERSION': '1.0'}, 'sub-vars': {'SUB_VERSION': '2.0'}, 'environment': {'SUB_VERSION': '2.0', 'VERSION': '1.0'}}}}
```

**Expected Behavior**
The `environment` key contains the merged `variables` and `subvars` mappings from `bar.yml`:

```yml
'environment': {'SUB_VERSION': '2.0', 'VERSION': '1.0'}
```

**General Notes**

Didn't look into this too hard, but [`config.py`](https://github.com/JonathonReinhart/scuba/blob/93aef163e109580b1e1d2ba66174a7c1264f5d2c/scuba/config.py) defines `from_yaml` and uses `construct_scalar`, which is probably related.
