### ISSUE TITLE
GitLab CI yaml includes custom tags that cannot be resolved by from_yaml 

### ISSUE THREAD

**Issue by haboustak** [JonathonReinhart/scuba#200]
GitLab has added a custom yaml tag: [!reference](https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags). This tag copies content from another path within the yaml document. The example use cases are to reuse script blocks in other CI jobs. Implementation in ruby is here: [lib/gitlab/ci/config/yaml/tags/reference.rb](https://gitlab.com/gitlab-org/gitlab/-/blob/436d642725ac6675c97c7e5833d8427e8422ac78/lib/gitlab/ci/config/yaml/tags/reference.rb#L8)

I've created an [example project](https://gitlab.com/haboustak/test-ci-reference/) based on the above documentation.

It seems appropriate to create a `!from_gitlab` custom tag to load GitLab-specific yaml syntax. This would use a `SafeLoader` with support for `!reference` initially. It would also provide a place for `scuba` to support some or all of GitLab's `include` syntax.

**Sample `.gitlab-ci.yml`**
```yaml
stages:
  - build

.before:
  script:
    - echo "ABCD"

build:
  stage: build
  script:
    - !reference [.before, script]
    - echo "after ABCD completes"
```
