### ISSUE TITLE
Mirror host-side user home directory rather than hard-coding `/home`

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/scuba#216]
Currently, when `scubainit`  creates the users's `$HOME` directory (in the container):
https://github.com/JonathonReinhart/scuba/blob/c6f3e625707aee11898079770b455a3d135ac019/scubainit/scubainit.c#L650-L653

It uses a hard-coded `/home`:
https://github.com/JonathonReinhart/scuba/blob/c6f3e625707aee11898079770b455a3d135ac019/scubainit/scubainit.c#L30-L30

This works, but creates a dissonance if the users's real (host) homedir is set to something other than `/home`. This is especially apparent when using `$HOME` in `volumes`:
```yaml
volumes:
  $HOME/.gitconfig:                    # container path
    hostpath: $HOME/.gitconfig         # host path
    options: ro
```

Since `$HOME` is expanded in the host environment, it is wrong inside the container.

Now, similar to #213, we could add a `SCUBA_USER_HOME` variable which expands to the same thing used by `scubainit`. But I think it's easier to reason about if `$HOME` follows the same pattern as `$PWD` and the host and container paths match (even if `$HOME` isn't mounted automatically.)
