### ISSUE TITLE
Support GitLab CI's 'image' dictionary format

### ISSUE THREAD

**Issue by xanarin** [JonathonReinhart/scuba#230]
GitLab CI supports both a bare string and a dictionary for the `image` key. [This is their reference](https://docs.gitlab.com/ee/ci/yaml/#image) for the possible values of an `image` key. Scuba should support this format (as much as it is able) so that a developer can `!from_yaml .gitlab-ci.yml myjob.image` without concern of Scuba not being able to understand the dictionary and its keys.

Some examples of legitimate uses of `image` according to GitLab's documentation:

- Bare string
  ```yaml
  build_all:
    image: "xanarin/base-build:1.17"
    script: "make -j24"
  ```

- Dictionary with image name:
  ```yaml
  build_all:
    image:
      name: "xanarin/base-build:1.17"
    script: "make -j24"
  ```

- Dictionary with entrypoint:
  ```yaml
  build_all:
    image:
      name: "xanarin/base-build:1.17"
      entrypoint: ["/usr/bin/bash", "/opt/run_with_env.sh"]
    script: "make -j24"
  ```

- Dictionary with "pull policy" (can have value `always`, `if-not-present`, or `never`)
  ```yaml
  build_all:
    image:
      name: "xanarin/base-build:1.17"
      pull_policy: always
    script: "make -j24"
  ```

- Dictionary with pull policy array
  ```yaml
  build_all:
    image:
      name: "xanarin/base-build:1.17"
      pull_policy: [always, if-not-present]
    script: "make -j24"
  ```

I don't know if Scuba should to fully support the `pull_policy` directive (in the sense that it obeys the policy), but at a minimum I think Scuba shouldn't error out if it encounters that directive.
