### ISSUE TITLE
Allow command aliases to be associated with images

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/scuba#26]
This builds upon #60, which allows for aliases to be multiline scripts, and also allows those aliases to run with a different Docker image.

Example `.scuba.yml`:
```yaml
image: default_image_if_not_overridden
aliases:
  foo: simple alias string
  bar:
    image: this overrides the top-level image
    script: a simple script
  snap:
    image: this overrides the top-level image
    script:
      - a complex script
      - with multiple commands
```

By using this schema, we can `!from_yaml` an entire alias definition directly from a [`.gitlab-ci.yml`] file. This allows scuba behave somewhat like a local CI runner.

[`.gitlab-ci.yml`]: http://doc.gitlab.com/ce/ci/yaml/README.html
