### ISSUE TITLE
Enhanced aliases

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/scuba#60]
Allow complex, multi-line aliases, using the [common script schema](https://github.com/JonathonReinhart/scuba/blob/master/doc/yaml-reference.md#common-script-schema), like this:

```yaml
image: foo
aliases:
  build:
    script:
      - echo "build script starting"
      - make -j4
      - other stuff
```

When an alias is used, a script will be generated from it and injected into the container for execution.

*If an alias is a multiline script, then no additional arguments will be allowed in the scuba invocation.*

A somewhat important change made by this is that *all aliases will now be executed by a shell*, instead of directly, as before. This alone may warrant a v2.0 bump, and we should then probably execute everything (even non-aliases) via the shell.
